### ISSUE TITLE
トップページのメインカテゴリをモバイルに対応させる

### ISSUE THREAD

**Issue by MORIMOTO520212** [MORIMOTO520212/iput-circle-hp#53]
## 課題
トップページのメインカテゴリがPCサイズにしか対応しておらず、デザインは出来上がっているもののまだスマホサイズで対応していません。ずっと後回しにしていました。

## 作業
トップページのメインカテゴリをスマホに対応するようにコーディングをお願いします。ずっと後回しにしていました。
デザインはXDから確認してください。
レスポンシブのやり方はサークルカテゴリの方法でお願いします。

## 期待する動作
lgサイズでPC表示が消えるので、その時にモバイル表示に切り替えてください。

<img src="https://user-images.githubusercontent.com/28892090/230343301-01c55319-4d03-4807-97d0-02c7ee58d43c.png" width="20%" />

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
これは既存のtop-categoryとは別で作成し、d-lg-noneなどでリスポンシブにしますか？

**Comment by MORIMOTO520212** [comment]
はい、それでお願いします。

**Comment by MORIMOTO520212** [comment]
**実装完了**  

<img src="https://user-images.githubusercontent.com/28892090/230410435-3822a9a5-0cad-440c-8fba-f58f99636a80.png" width="50%" />
