### ISSUE TITLE
メール送信のスパム判定をGASを用いて回避するシステムを作ってください。

### ISSUE THREAD

**Issue by MORIMOTO520212** [MORIMOTO520212/iput-circle-hp#55]
## 課題
現在、メール送信はサーバーのphpから行っていますが、受け取り側でスパムメールと判断されてしまっている状況です。  
迷惑メールに振り分けられるため、閲覧しない人がほとんどでした。  
そのため、Google App Scriptからメール送信をすることでスパム判定を回避します。

## 作業
主に、ユーザー登録のメールアドレス確認メールでスパム対策を優先したいです。  
PHPから宛先、件名、本文をGASにPOSTし、GAS側でGmailAppクラスを用いてメールを送信するようにしてください。  
送信元メールアドレスは`iputone.staff@gmail.com`です。  
IPUT ONEへの組み込みはこちらで行うので、PHPとGASのコードが書けたらファイルとしてmaster-wordpressブランチにcommitしてください。  

*GASでのメール送信は以下のサンプルコードを参考にしてください。
```gs
function sendMail() {
  // メール設定
  const recipient = 'example@gmail.com'; // To 宛先
  const subject = 'テスト送信';                 // Subject 件名
  const body = 'テスト送信ボディー';             // Body 本文
  const options = {
    from: 'iputone.staff@gmail.com', // From 送信元
    cc: 'iputone.staff@gmail.com',   // Cc カーボンコピー
    name: 'IPUT ONE制作チーム',       // ユーザー名
  };
  
  // メール送信
  GmailApp.sendEmail(recipient, subject, body, options);
}
```

*phpでのPOSTリクエストは以下のサイトを参照してください。
- [【GAS】PHPからPOST送信したデータをスプレッドシートに保存する](https://into-the-program.com/gas-set-data-post-php-to-spreadsheet/)

## 期待する動作
phpで設定された宛先と件名、本文をphpを実行することで、GASを介してメール送信できるようにしてください。

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
これってブランチ切らなくて、別のフォルダーを作ってフォルダごとコミットする感じですか？

**Comment by MORIMOTO520212** [comment]
@3k11ooo 
新しく一時的なフォルダーを作成してください。名前はなんでもいいです。

**Comment by 3k11ooo** [comment]
了解いたしました！

**Comment by 3k11ooo** [comment]
> @3k11ooo 新しく一時的なフォルダーを作成してください。名前はなんでもいいです。

@MORIMOTO520212 
かしこまりました。

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
構造に関する質問です。
（メール送信が必要となる）処理が行われたのち、GASへ必要な情報をpostして、GASからメールを送信するのかと想像していますが、フォームで入力されたデータ（名前やメールアドレス？）はスプレッドシートに保存するのでしょうか？

**Comment by 3k11ooo** [comment]
> どちらがいいでしょうか。お問い合わせフォームもメール送信しようと考えてました。

@MORIMOTO520212 
その辺の仕組みをあまり理解していないのでわからないです、、、、。
メールを送信するタイミングでJSONデータを引数にしてPOSTする関数に渡してって感じを想像してました。

**Comment by MORIMOTO520212** [comment]
はい、それでお願いします。

**Comment by MORIMOTO520212** [comment]
完了
