### ISSUE TITLE
トップページのインフォメーションでモバイル表示が崩れているので修正してください。

### ISSUE THREAD

**Issue by MORIMOTO520212** [MORIMOTO520212/iput-circle-hp#56]
## 課題
タイトル部分のはみ出しはoverflow: hiddenが適用されていないことが原因だと考えられます。  
また、日付部分が改行されているので改行されないように修正をお願いします。  
タイトルのフォントサイズを16px、  
抜粋文のフォントサイズを14pxに変更してください。  

<img src="https://user-images.githubusercontent.com/28892090/230527869-72433871-3c4c-4535-86ff-d818888380e9.png" width="30%" />

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
トップページの新着情報の欄がうまく表示されていないのですが、理由わかりますか。
![image](https://user-images.githubusercontent.com/84764077/230535121-8c17b6b9-420e-4388-b4bb-125a84738897.png)

**Comment by MORIMOTO520212** [comment]
一度記事をすべて消して、マイページから仮の記事を作成してみてください。
原因としては、古い記事のデータに新しく追加したpermissionレコードがないのが原因だと思います。

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
かしこまりました。
ありがとうございます。

**Comment by 3k11ooo** [comment]
@MORIMOTO520212 
記事を作成しなおしたのですが、エラーが出ており、var_dumpで確認したところ以下の結果でした。これの意味を理解できていないので、教えてください。
![image](https://user-images.githubusercontent.com/84764077/230541546-9d385178-6734-41f9-b055-32319ac6e0e5.png)
![image](https://user-images.githubusercontent.com/84764077/230541580-b5b015ad-0e1d-45ba-a076-ce0ec160cb9c.png)

**Comment by MORIMOTO520212** [comment]
Edit Lockプラグインが影響しているのではないでしょうか。

**Comment by 3k11ooo** [comment]
> Edit Lockプラグインが影響しているのではないでしょうか。

今回のイシューには直接関係がないので、私の環境が原因だと思うので修正しておきます。

**Comment by MORIMOTO520212** [comment]
@3k11ooo 
タイトルのフォントサイズを16px、
抜粋文のフォントサイズを14pxにしてみてください。
少し文字が大きすぎた気がします。

**Comment by 3k11ooo** [comment]
強引なやり方なんですけど、ここで設定してるんですけど、これまずいですか？
![image](https://user-images.githubusercontent.com/84764077/230735140-05586c00-427e-44b2-a265-9ee3bce08916.png)

**Comment by MORIMOTO520212** [comment]
ありがとうございます。
